version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "4000:4000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  filter:
    build:
      context: ./Filter
    depends_on:
      - nats

  dashboard:
    build:
      context: ./Dashboard
    depends_on:
      - nats
      - influxdb
  
  command:
    build:
      context: ./Command
    restart: always
    ports:
      - "8080:8080"
      - "3000:3000"
